config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [ :new, :create ]
  end
  resources :reviews, only: [ :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, :address, :category, :phone_number, presence: true
  validates :category, inclusion: {in:["chinese", "italian", "japanese", "french", "belgian"]}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5], allow_nil: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
before_action :find_restaurant, only:[:show, :edit, :update, :destroy]
  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private
  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
before_action :find_restaurant, except: [:destroy]

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def new
    @review = Review.new
  end

  def destroy
    @review = Review.find(params[:id]) # review ID param, if a restaurant is destroyed, associated review with it is destroyed.
    @review.destroy
    redirect_to restaurant_path(@review.restaurant)
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<div class="container">
  <h3 style="text-align:center">Edit a Restaurant</h3>

  <%= simple_form_for(@restaurant) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category %>
    <%= f.submit class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/restaurants/index.html.erb
<div class= "container">
  <h1 style="text-align:center">The List of All Restaurants</h1>
    <p style="text-align:center">
      <%= link_to'Create', new_restaurant_path %>
      <%# <%= link_to 'Update', restaurant_path(restaurant) %>
      <%# <%= link_to 'Edit', edit_restaurant_path(@restaurant)%>
      <%# <%= link_to 'Delete', restaurant %>
    </p>
<hr>
  <% @restaurants.each do |restaurant| %>
  <h5> 🍽 <%= link_to restaurant.name, restaurant_path(restaurant) %> | <%= restaurant.category %></h5>
    <p> ☎️ Contact Info:  <%= restaurant.address %>, <%=restaurant.phone_number %> </p>
  <% end %>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <h3 style="text-align:center">Create a New Restaurant</h3>

  <%= simple_form_for(@restaurant) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category %>
    <%= f.submit class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <h2 style="text-align: center" >🍽 <%= @restaurant.name %></h2>
    <p style="text-align: center">
      <strong>Category: <%= @restaurant.category %></strong> |
      <strong>Contact: <%= @restaurant.address %> , <%= @restaurant.phone_number %></strong>
    </p>
  <hr>

   <ul class="list-group">
      <% @restaurant.reviews.each do |review| %>
        <li class="list-group-item">
          <p>Review: <%= review.content %></p>
          <p>Rating: <%= review.rating %></p>
          <%= link_to "Remove",
          review_path(review),
          method: :delete,
          data: { confirm: "Are you sure?" } %>
        </li>
      <% end %>
    </ul>

    <p>
      <%= link_to 'back', restaurants_path %> |
      <%= link_to 'edit this restaurant', edit_restaurant_path(@restaurant) %> |
      <%= link_to 'delete this restaurant', restaurant_path(@restaurant),method: :delete,
      data: { confirm: 'Are you sure?'} %> |
      <%= link_to 'add a review', new_restaurant_review_path(@restaurant) %>
    </p>


</div>

app/views/reviews/new.html.erb
<div class="container">
  <h3 style="text-align:center">⭐️ Leave a Review</h3>

  <%= simple_form_for [ @restaurant, @review ] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating %>
    <%= f.submit "submit a review", class: 'btn btn-primary'%>
  <% end %>
</div>